version: '3.7'

volumes:
  pgdata:
  caddy_data:
    external: true
  caddy_config:

services:
  caddy:
    image: ferch5003/sm-micro-caddy:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  backend:
    image: ferch5003/sm-backend:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "3000:80"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres-bot

  frontend:
    image: ferch5003/sm-frontend:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

  postgres-bot:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store-manager-bot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata/histories.sql:/docker-entrypoint-initdb.d/histories.sql
    user: '${UID}:${GID}'