version: '3.7'

volumes:
  pgdata:

services:
  backend:
    image: ferch5003/sm-backend:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "3002:80"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres-bot
    networks:
      - smb_app_default
      - caddy_network

  frontend:
    image: ferch5003/sm-frontend:1.0.0
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - smb_app_default
      - caddy_network

  postgres-bot:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store-manager-bot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata/histories.sql:/docker-entrypoint-initdb.d/histories.sql
    user: '${UID}:${GID}'
    networks:
      - smb_app_default
      - caddy_network

networks:
  smb_app_default:
    driver: overlay
  proxy:
    external: true