CREATE TABLE "histories"(
    "id" SERIAL NOT NULL,
    "user_message" TEXT NOT NULL,
    "bot_response" TEXT NOT NULL,
    "feedback" BOOLEAN NOT NULL,
    "timestamp" TIMESTAMP(0) WITHOUT TIME ZONE NULL DEFAULT NOW()
);
ALTER TABLE
    "histories" ADD PRIMARY KEY("id");

INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (1,'Quiénes somos','Deal Genius se encarga de tomar los mensajes y automatizar las respuestas de articulos provenientes de Amazon para ayudarle al usuario a obtener articulos que necesite al mejor precio. Refernte a Amazon se guía por cuatro principios: la obsesión por el cliente, la pasión por la innovación, el compromiso con la excelencia operativa y el pensamiento a largo plazo. Nos esforzamos por ser la empresa más centrada en el cliente del mundo, la mejor empleadora y el lugar más seguro para trabajar. Las opiniones de los clientes, las compras en un solo clic, las recomendaciones personalizadas, el servicio Prime, la Logística de Amazon, AWS, la autopublicación Kindle Direct Publishing, Kindle, el programa de formación Career Choice, los dispositivos Fire, Fire TV, Amazon Echo, Alexa, la tecnología Just Walk Out, Amazon Studios o The Climate Pledge son algunos ejemplos en los que Amazon ha sido pionera.','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (2,'Que puedo consultar','Deal Genius brinda articulos de la pagina https://www.amazon.com/-/es/','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (3,'Que es Alkosto','Lo siento, no podria decirte algo referente diferente a Amazon','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (4,'Como puedo vender productos en Amazon','Desde Amazon Sell puedes ganar dinero con los productos referidos a Amazon https://sell.amazon.com/es','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (5,'Principio de liderazgo','Ya seas manager de un equipo grande o trabajes de manera individual, eres un líder en Amazon. A menos que conozcas otros mejores, estos son nuestros principios de liderazgo. Actúa como líder.','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (6,'Pasión por los clientes','Las personas líderes piensan primero en los clientes y trabajan de acuerdo a este principio. Ponen todo su empeño en ganarse su confianza y mantenerla. Aunque prestan atención a la competencia, lo que realmente les apasiona son los clientes.','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (7,'Responsabilidad y compromiso','Las personas líderes son dueñas. Tienen visión de futuro y no sacrifican los valores a largo plazo por resultados inmediatos. Actúan en nombre de toda la compañía, sin limitarse a su propio equipo. Nunca dicen “ese no es mi trabajo”.','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (8,'Inventar y simplificar','Las personas líderes esperan y demandan innovación e invención por parte de sus equipos y siempre encuentran maneras de simplificar. Se mantienen informadas de lo que ocurre a su alrededor, buscan nuevas ideas en todas partes y no están limitadas por el “no lo hemos inventado aquí”. Al ser innovadoras, aceptan que pueden ser incomprendidas durante mucho tiempo.','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (9,'Tener razón, casi siempre','Las personas líderes, casi siempre tienen razón. Tienen buen criterio e intuición. Están abiertas a escuchar opiniones distintas y cuestionan sus propias creencias.','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (10,'Aprender y tener curiosidad','Las personas líderes nunca lo dan todo por aprendido y siempre tratan de mejorar. Muestran curiosidad por conocer y explorar nuevas posibilidades.','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (11,'Quiero saber los primeros 5 audifonos inalambricos de la pagina','Si claro, te dejo una la siguiente lista:
- https://www.amazon.com/-/es/Auriculares-Bluetooth-B8-auriculares-inalámbricos/dp/B0CFV9XR2Q/ref=sr_1_1?crid=1ITQ2RGKAK7UC&dib=eyJ2IjoiMSJ9.5_1G9wKQezhinEY6KaZiuvBXl8Xd_aKIltTaTX-yniaCeSREPGAblU27qszry_7e_9bO8bO9-ADhGbGRiY6zlslM2UXSnOZj3xjwGXEJD-UwFibHcSd1S64wJLjOArsHdB54CfxEXz5lTuBXTynJG8R0vBvJedgSJc0tvko97v4O_deZ9nNJ8FF4e6eflFtKUp-h715hq19_1ExANyaRBi5wAudfmWDvg0vlLgbINIo.xvSfZp3cxtw4UXXUZQ4rjJtn5swGsjvLV2IQt-1vtC0&dib_tag=se&keywords=audifonos+inalambricos&qid=1722221905&sprefix=audifonos%2Caps%2C173&sr=8-1
- https://www.amazon.com/-/es/Auriculares-reproducción-ecualizador-auriculares-inalámbricos/dp/B09LYF2ST7/ref=sr_1_2?crid=1ITQ2RGKAK7UC&dib=eyJ2IjoiMSJ9.5_1G9wKQezhinEY6KaZiuvBXl8Xd_aKIltTaTX-yniaCeSREPGAblU27qszry_7e_9bO8bO9-ADhGbGRiY6zlslM2UXSnOZj3xjwGXEJD-UwFibHcSd1S64wJLjOArsHdB54CfxEXz5lTuBXTynJG8R0vBvJedgSJc0tvko97v4O_deZ9nNJ8FF4e6eflFtKUp-h715hq19_1ExANyaRBi5wAudfmWDvg0vlLgbINIo.xvSfZp3cxtw4UXXUZQ4rjJtn5swGsjvLV2IQt-1vtC0&dib_tag=se&keywords=audifonos+inalambricos&qid=1722221905&sprefix=audifonos%2Caps%2C173&sr=8-2
- https://www.amazon.com/-/es/Auriculares-inalámbricos-reproducción-inalámbrica-auriculares/dp/B0D7CSJTGQ/ref=sr_1_3?crid=1ITQ2RGKAK7UC&dib=eyJ2IjoiMSJ9.5_1G9wKQezhinEY6KaZiuvBXl8Xd_aKIltTaTX-yniaCeSREPGAblU27qszry_7e_9bO8bO9-ADhGbGRiY6zlslM2UXSnOZj3xjwGXEJD-UwFibHcSd1S64wJLjOArsHdB54CfxEXz5lTuBXTynJG8R0vBvJedgSJc0tvko97v4O_deZ9nNJ8FF4e6eflFtKUp-h715hq19_1ExANyaRBi5wAudfmWDvg0vlLgbINIo.xvSfZp3cxtw4UXXUZQ4rjJtn5swGsjvLV2IQt-1vtC0&dib_tag=se&keywords=audifonos+inalambricos&qid=1722221905&sprefix=audifonos%2Caps%2C173&sr=8-3
- https://www.amazon.com/-/es/Auriculares-inalámbricos-reproducción-auriculares-impermeable/dp/B0CPJG173J/ref=sr_1_4?crid=1ITQ2RGKAK7UC&dib=eyJ2IjoiMSJ9.5_1G9wKQezhinEY6KaZiuvBXl8Xd_aKIltTaTX-yniaCeSREPGAblU27qszry_7e_9bO8bO9-ADhGbGRiY6zlslM2UXSnOZj3xjwGXEJD-UwFibHcSd1S64wJLjOArsHdB54CfxEXz5lTuBXTynJG8R0vBvJedgSJc0tvko97v4O_deZ9nNJ8FF4e6eflFtKUp-h715hq19_1ExANyaRBi5wAudfmWDvg0vlLgbINIo.xvSfZp3cxtw4UXXUZQ4rjJtn5swGsjvLV2IQt-1vtC0&dib_tag=se&keywords=audifonos+inalambricos&qid=1722221905&sprefix=audifonos%2Caps%2C173&sr=8-4','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (12,'El gaming keyboard mas barato de la pagina','Aqui te dejo esta opción:
- Teclado para juegos al 65%, mini teclado retroiluminado con cable, ultracompacto, anti-fantasma, sin conflictos, 68 teclas, teclado con cable de membrana para juegos para PC, laptop, Mac: https://www.amazon.com/-/es/GEODMAER-retroiluminado-ultracompacto-anti-fantasma-conflictos/dp/B0D3CZYCH2/ref=sr_1_81?_encoding=UTF8&content-id=amzn1.sym.8148f1e1-83ed-498f-85be-ff288b197da7&dib=eyJ2IjoiMSJ9.FhAwj13XzCIDleP0DMVLAkmMHdg6FqTCIQtDgHgfYvG9qcgnfrqfFZQNc-oi4bSK1mevut1OPK5eX4OtjEuc-g.8N1e4MvOP4rKO6jWuH3FPwnoYWshgkh3La65da1YeS0&dib_tag=se&keywords=gaming+keyboard&pd_rd_r=038703fa-7a70-4ef2-b137-6d8a93a62e4d&pd_rd_w=PkFG1&pd_rd_wg=NRa7W&pf_rd_p=8148f1e1-83ed-498f-85be-ff288b197da7&pf_rd_r=AAR5VJM129TVZCYXXJN7&qid=1722222148&sr=8-81','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (13,'Pensar en grande','Pensar en pequeño se traduce en resultados pequeños. Las personas líderes crean y transmiten retos audaces que inspiran resultados. Piensan diferente y se anticipan a las necesidades de los clientes para encontrar nuevas maneras de darles un mejor servicio.','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (14,'Ganarse la confianza','Las personas líderes escuchan atentamente, hablan con franqueza y son respetuosas. Son abiertamente autocríticas, incluso si esto las pone en una situación difícil o incómoda. Las personas líderes son conscientes de que ni ellas ni su equipo huelen a rosas. Se comparan a sí mismas y a su equipo con los mejores.','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (15,'Tener determinación; discrepar y comprometerse','Las personas líderes están obligadas a cuestionar las decisiones de forma respetuosa cuando no están de acuerdo, aunque sea incómodo o agotador. Ser líder significa mostrar determinación y tenacidad. No ceder ante la presión del grupo solo para lograr la armonía en su equipo. Cuando se toma una decisión, la apoyan totalmente.','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (16,'El gaming keyboard mas carode la pagina','Aqui te dejo esta opción:
- Teclado para juegos personalizado ROG Azoth Extreme 75, Chasis de aluminio, Placa de posicionamiento de fibra de carbono, Montaje de junta ajustable, Amortiguación de tres capas, Pantalla táctil OLED: https://www.amazon.com/-/es/personalizado-aluminio-posicionamiento-ajustable-Amortiguación/dp/B0D45ZHYZJ/ref=sr_1_5?_encoding=UTF8&content-id=amzn1.sym.8148f1e1-83ed-498f-85be-ff288b197da7&dib=eyJ2IjoiMSJ9.krBy_or9DvoELz_22R-AzSbN3S0PH9Eh5Op0rKuak6K4AJikNt8-Ok0OePq01_LXXTVtYMCMjiJZz-N8dsUqDNoPUh2MSDIv1x6UgWAw7wCY4qo7kaTRB2MXxolqsDe0-XRegtBBa0Q1H4QQcG9FRFU4pjxV5sHxo0JRyKQWxGsRvJyEqwcUEXBFIM4PbLUejiuyCZr58B7xsPz2lRPGls1F-PCaaB5X1dYhUbwxe_4.KxhIFyJOb2e0aswg8dULZ0Dk9kGhJwsXk8doL2ALPaY&dib_tag=se&keywords=gaming+keyboard&pd_rd_r=038703fa-7a70-4ef2-b137-6d8a93a62e4d&pd_rd_w=PkFG1&pd_rd_wg=NRa7W&pf_rd_p=8148f1e1-83ed-498f-85be-ff288b197da7&pf_rd_r=AAR5VJM129TVZCYXXJN7&qid=1722222255&sr=8-5','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (17,'Obtener resultados','Las personas líderes se centran en los elementos clave para su negocio y obtienen resultados de calidad a tiempo. A pesar de las dificultades, están a la altura de las circunstancias y nunca se conforman.','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (18,'Premios y reconocimientos','Desde el primer día, nos hemos esforzado por ser la empresa más centrada en el cliente del mundo. El trabajo que realizamos para nuestros clientes, empleados y las comunidades en las que viven ha obtenido distintos reconocimientos a nivel nacional e internacional. A continuación, te presentamos algunos de ellos.','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (19,'Empleados','En España, Amazon ha sido reconocida como “Top Employer 2021” y "Top Employer 2022" por la calidad del entorno laboral y los programas de recursos humanos ofrecidos a los empleados de Amazon en el país. La compañía también ha sido seleccionada por Randstad como “la empresa más atractiva para trabajar en España” y ha sido incluida por LinkedIn en su primera lista “Top Companies: las 25 mejores empresas para trabajar en España”.','FALSE',NULL);
INSERT INTO histories(id,user_message,bot_response,feedback,timestamp) VALUES (20,'Clientes','Primer puesto en la categoría de marca internacional más valorada según BrandZ, 2019-2020
Segundo puesto en la categoría Brand Finance Global 500 como marca más valorada del mundo, 2021
Primer puesto en la categoría de las 50 empresas más comprometidas, 2017 según Forbes
Primer puesto en la categoría de empresa más fiable según Fortune 100, 2016.
Segundo puesto en la categoría de empresas más admiradas del mundo, 2017-2021, según Fortune.
Segundo puesto en la categoría de mejor marca internacional según Interbrand, 2020.
Segundo puesto en el ranking del Reputation Institute US RepTrak® 100 como la empresa más valorada, 2017
Tercer puesto otorgado por el Boston Consulting Group a las empresas más innovadoras, 2021
Cuarto puesto en el ranking de las marcas más valoradas del mundo, 2019-2020, elaborado por Forbes
Quinto puesto en el ranking de las marcas más fiables del mundo elaborado por Morning Consult, 2021
Quinto puesto en la categoría de mejor marca internacional según YouGov, 2020
Nombrada entre las empresas más influyentes, 2021, de la revista TIME
Nombrada entre las empresas más justas de la categoría JUST 100 por JUST Capital, 2018-2021
Reconocimiento a la inclusión Disability:IN como empresa innovadora del año, 2019.','FALSE',NULL);

SELECT setval('histories_id_seq', max(id)) FROM histories;